//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursovaya
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class strah_compEntities : DbContext
    {
        private static strah_compEntities _context;

        public strah_compEntities()
            : base("name=strah_compEntities")
        {
        }

        public static strah_compEntities GetContext()
        {
            if (_context == null)
            {
                _context = new strah_compEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<dogovors> dogovors { get; set; }
        public virtual DbSet<fillials> fillials { get; set; }
        public virtual DbSet<sotrud> sotrud { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<type_of_str> type_of_str { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
