//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class dogovors
    {
        public int id { get; set; }
        public string date_start { get; set; }
        public string date_end { get; set; }
        public Nullable<double> str_proc { get; set; }
        public double str_pay { get; set; }
        public int id_client { get; set; }
        public int id_type_of { get; set; }
        public int id_sotrud { get; set; }
        public int id_fillials { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual fillials fillials { get; set; }
        public virtual sotrud sotrud { get; set; }
        public virtual type_of_str type_of_str { get; set; }
    }
}
