//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class sotrud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sotrud()
        {
            this.dogovors = new HashSet<dogovors>();
        }
    
        public int id { get; set; }
        public string fio_sotrud { get; set; }
        public string pol { get; set; }
        public string dolzhnost { get; set; }
        public string phone_number { get; set; }
        public int id_fillial { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dogovors> dogovors { get; set; }
        public virtual fillials fillials { get; set; }
    }
}
